export type Food = {
  id: string;
  name: string;
  category: 'Fruit' | 'Vegetable' | 'Protein' | 'Grains' | 'Beverage' | 'Local Dish' | 'Snack';
  image: string;
  imageHint: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  nutrients: {
    fiber: number;
    iron: number;
    vitaminA: number;
    sodium: number;
  };
  description: string;
  tags: string[];
};


export const mockUser = {
  name: "Akua",
  email: "akua.g@example.com",
  onboardingCompleted: true,
  profilePictureUrl: "https://picsum.photos/seed/akua/100/100",
};

export const mockFoods: Food[] = [
  {
    id: "jollof-rice",
    name: "Jollof Rice",
    category: "Local Dish",
    image: "https://picsum.photos/seed/jollof/400/300",
    imageHint: "jollof rice",
    calories: 410,
    protein: 9,
    carbs: 70,
    fat: 10,
    description: "A popular West African one-pot rice dish, known for its vibrant red color and deep flavor.",
    nutrients: {
      fiber: 4,
      iron: 2.5,
      vitaminA: 150,
      sodium: 800,
    },
    tags: ["Local"],
  },
  {
    id: "fufu-and-light-soup",
    name: "Fufu & Light Soup",
    category: "Local Dish",
    image: "https://picsum.photos/seed/fufu/400/300",
    imageHint: "fufu soup",
    calories: 550,
    protein: 25,
    carbs: 80,
    fat: 15,
    description: "A staple food made from cassava and plantain, served with a flavorful, spicy tomato-based soup.",
    nutrients: {
      fiber: 8,
      iron: 4,
      vitaminA: 200,
      sodium: 1200,
    },
    tags: ["Local"],
  },
  {
    id: 'banku-and-tilapia',
    name: 'Banku and Tilapia',
    category: 'Local Dish',
    image: 'https://picsum.photos/seed/banku/400/300',
    imageHint: 'banku tilapia',
    calories: 680,
    protein: 45,
    carbs: 65,
    fat: 25,
    description: 'Fermented corn and cassava dough served with grilled tilapia, hot pepper, and shito.',
    nutrients: { fiber: 7, iron: 3, vitaminA: 40, sodium: 950 },
    tags: ['Local', 'High Protein'],
  },
  {
    id: 'waakye',
    name: 'Waakye',
    category: 'Local Dish',
    image: 'https://picsum.photos/seed/waakye/400/300',
    imageHint: 'waakye rice',
    calories: 720,
    protein: 22,
    carbs: 110,
    fat: 20,
    description: 'A hearty dish of rice and beans cooked with sorghum leaves, served with various accompaniments.',
    nutrients: { fiber: 15, iron: 5, vitaminA: 10, sodium: 1100 },
    tags: ['Local'],
  },
  {
    id: 'kelewele',
    name: 'Kelewele',
    category: 'Snack',
    image: 'https://picsum.photos/seed/kelewele/400/300',
    imageHint: 'spicy plantain',
    calories: 320,
    protein: 2,
    carbs: 55,
    fat: 12,
    description: 'Spicy fried plantain seasoned with ginger, garlic, and cayenne pepper.',
    nutrients: { fiber: 4, iron: 1, vitaminA: 80, sodium: 300 },
    tags: ['Local', 'Vegan'],
  },
  {
    id: "grilled-tilapia",
    name: "Grilled Tilapia",
    category: "Protein",
    image: "https://picsum.photos/seed/tilapia/400/300",
    imageHint: "grilled fish",
    calories: 250,
    protein: 40,
    carbs: 2,
    fat: 10,
    description: "Whole tilapia fish marinated in spices and grilled to perfection, often served with banku or kenkey.",
    nutrients: {
      fiber: 0,
      iron: 1.5,
      vitaminA: 50,
      sodium: 400,
    },
    tags: ["High Protein", "Low Carb"],
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast (Grilled)',
    category: 'Protein',
    image: 'https://picsum.photos/seed/chicken/400/300',
    imageHint: 'grilled chicken',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    description: 'A lean source of protein, grilled without skin.',
    nutrients: { fiber: 0, iron: 1, vitaminA: 10, sodium: 74 },
    tags: ['High Protein', 'Low Carb', 'Halal'],
  },
   {
    id: 'lentils',
    name: 'Lentils (Cooked)',
    category: 'Protein',
    image: 'https://picsum.photos/seed/lentils/400/300',
    imageHint: 'cooked lentils',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    description: 'A versatile legume, great source of plant-based protein and fiber.',
    nutrients: { fiber: 8, iron: 3.3, vitaminA: 5, sodium: 2 },
    tags: ['High Protein', 'Vegan'],
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/apple/400/300',
    imageHint: 'red apple',
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    description: 'A crisp and sweet fruit, rich in fiber and vitamin C.',
    nutrients: { fiber: 4.4, iron: 0.2, vitaminA: 5, sodium: 2 },
    tags: ['Vegan'],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/banana/400/300',
    imageHint: 'ripe banana',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    description: 'A popular fruit known for its potassium content and natural sweetness.',
    nutrients: { fiber: 3.1, iron: 0.3, vitaminA: 8, sodium: 1 },
    tags: ['Vegan'],
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/mango/400/300',
    imageHint: 'sliced mango',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    description: 'A sweet tropical fruit, excellent source of Vitamin A and C.',
    nutrients: { fiber: 1.6, iron: 0.2, vitaminA: 54, sodium: 1 },
    tags: ['Vegan'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetable',
    image: 'https://picsum.photos/seed/broccoli/400/300',
    imageHint: 'broccoli florets',
    calories: 55,
    protein: 3.7,
    carbs: 11,
    fat: 0.6,
    description: 'A green vegetable high in fiber, vitamin C, and vitamin K.',
    nutrients: { fiber: 5.1, iron: 1, vitaminA: 135, sodium: 50 },
    tags: ['Vegan', 'Low Carb'],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetable',
    image: 'https://picsum.photos/seed/spinach/400/300',
    imageHint: 'fresh spinach',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    description: 'A leafy green vegetable packed with iron, calcium, and vitamins.',
    nutrients: { fiber: 2.2, iron: 2.7, vitaminA: 469, sodium: 79 },
    tags: ['Vegan', 'Low Carb'],
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice (Cooked)',
    category: 'Grains',
    image: 'https://picsum.photos/seed/rice/400/300',
    imageHint: 'cooked rice',
    calories: 215,
    protein: 5,
    carbs: 45,
    fat: 1.8,
    description: 'A whole grain rice with a nutty flavor, high in fiber and minerals.',
    nutrients: { fiber: 3.5, iron: 0.8, vitaminA: 0, sodium: 10 },
    tags: ['Vegan'],
  },
  {
    id: 'oats',
    name: 'Oats (Rolled)',
    category: 'Grains',
    image: 'https://picsum.photos/seed/oats/400/300',
    imageHint: 'oats bowl',
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 2.5,
    description: 'A versatile whole grain often eaten as oatmeal.',
    nutrients: { fiber: 4, iron: 2, vitaminA: 0, sodium: 0 },
    tags: ['Vegan'],
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Beverage',
    image: 'https://picsum.photos/seed/water/400/300',
    imageHint: 'glass water',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    description: 'Essential for hydration.',
    nutrients: { fiber: 0, iron: 0, vitaminA: 0, sodium: 0 },
    tags: ['Vegan', 'Halal'],
  },
  {
    id: 'sobolo',
    name: 'Sobolo (Hibiscus Tea)',
    category: 'Beverage',
    image: 'https://picsum.photos/seed/sobolo/400/300',
    imageHint: 'hibiscus tea',
    calories: 50,
    protein: 0.2,
    carbs: 12,
    fat: 0,
    description: 'A refreshing Ghanaian drink made from hibiscus flowers, often flavored with ginger and pineapple.',
    nutrients: { fiber: 0, iron: 1, vitaminA: 5, sodium: 5 },
    tags: ['Local', 'Vegan'],
  },
];


export const healthQuotes = [
  "The greatest wealth is health.",
  "To keep the body in good health is a duty.",
  "Let food be thy medicine and medicine be thy food.",
  "A healthy outside starts from the inside.",
  "Take care of your body. It's the only place you have to live.",
];
