export type Food = {
  id: string;
  name: string;
  category: 'Fruit' | 'Vegetable' | 'Protein' | 'Grains' | 'Beverage' | 'Local Dish' | 'Snack';
  image: string;
  imageHint: string;
  calories: number; // Per 100g
  protein: number;  // Per 100g
  carbs: number;    // Per 100g
  fat: number;      // Per 100g
  nutrients: {
    fiber: number;
    sugar?: number;
    iron: number;
    calcium?: number;
    vitaminA: number;
    vitaminC?: number;
    sodium: number;
  };
  description: string;
  tags: string[];
};


export const mockUser = {
  name: "Akua",
  email: "akua.g@example.com",
  onboardingCompleted: true,
  profilePictureUrl: "https://picsum.photos/seed/akua/100/100",
};

export const mockFoods: Food[] = [
  {
    id: "jollof-rice",
    name: "Jollof Rice",
    category: "Local Dish",
    image: "https://picsum.photos/seed/jollof/400/300",
    imageHint: "jollof rice",
    calories: 180,
    protein: 4,
    carbs: 35,
    fat: 5,
    description: "A popular West African one-pot rice dish, known for its vibrant red color and deep flavor.",
    nutrients: {
      fiber: 2,
      sugar: 3,
      iron: 1.5,
      calcium: 20,
      vitaminA: 80,
      vitaminC: 10,
      sodium: 350,
    },
    tags: ["Local"],
  },
  {
    id: "fufu-and-light-soup",
    name: "Fufu & Light Soup",
    category: "Local Dish",
    image: "https://picsum.photos/seed/fufu/400/300",
    imageHint: "fufu soup",
    calories: 150, // per 100g of fufu, soup is separate
    protein: 1,
    carbs: 35,
    fat: 0.5,
    description: "A staple food made from cassava and plantain, served with a flavorful, spicy tomato-based soup.",
    nutrients: {
      fiber: 2,
      sugar: 1,
      iron: 0.8,
      calcium: 30,
      vitaminA: 10,
      sodium: 5, // Fufu only
    },
    tags: ["Local", "Gluten-Free"],
  },
  {
    id: 'banku-and-tilapia',
    name: 'Banku and Tilapia',
    category: 'Local Dish',
    image: 'https://picsum.photos/seed/banku/400/300',
    imageHint: 'banku tilapia',
    calories: 190, // Combined average
    protein: 15,
    carbs: 25,
    fat: 4,
    description: 'Fermented corn and cassava dough served with grilled tilapia, hot pepper, and shito.',
    nutrients: { fiber: 3, sugar: 2, iron: 2, calcium: 40, vitaminA: 20, sodium: 300 },
    tags: ['Local', 'High Protein'],
  },
  {
    id: 'waakye',
    name: 'Waakye',
    category: 'Local Dish',
    image: 'https://picsum.photos/seed/waakye/400/300',
    imageHint: 'waakye rice',
    calories: 290,
    protein: 10,
    carbs: 55,
    fat: 3,
    description: 'A hearty dish of rice and beans cooked with sorghum leaves, served with various accompaniments.',
    nutrients: { fiber: 8, sugar: 1, iron: 3, calcium: 50, vitaminA: 5, sodium: 400 },
    tags: ['Local', 'High Fiber'],
  },
  {
    id: 'kelewele',
    name: 'Kelewele',
    category: 'Snack',
    image: 'https://picsum.photos/seed/kelewele/400/300',
    imageHint: 'spicy plantain',
    calories: 250,
    protein: 1.5,
    carbs: 40,
    fat: 10,
    description: 'Spicy fried plantain seasoned with ginger, garlic, and cayenne pepper.',
    nutrients: { fiber: 3, sugar: 20, iron: 0.8, vitaminA: 60, vitaminC: 15, sodium: 250 },
    tags: ['Local', 'Vegan'],
  },
  {
    id: "grilled-tilapia",
    name: "Grilled Tilapia",
    category: "Protein",
    image: "https://picsum.photos/seed/tilapia/400/300",
    imageHint: "grilled fish",
    calories: 128,
    protein: 26,
    carbs: 0,
    fat: 2.6,
    description: "Whole tilapia fish marinated in spices and grilled to perfection, a lean protein source.",
    nutrients: {
      fiber: 0,
      sugar: 0,
      iron: 1,
      calcium: 100,
      vitaminA: 30,
      sodium: 380,
    },
    tags: ["High Protein", "Low Carb", 'Halal'],
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast (Grilled)',
    category: 'Protein',
    image: 'https://picsum.photos/seed/chicken/400/300',
    imageHint: 'grilled chicken',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    description: 'A lean source of protein, grilled without skin.',
    nutrients: { fiber: 0, sugar: 0, iron: 1, calcium: 15, vitaminA: 10, sodium: 74 },
    tags: ['High Protein', 'Low Carb', 'Halal'],
  },
   {
    id: 'lentils',
    name: 'Lentils (Cooked)',
    category: 'Protein',
    image: 'https://picsum.photos/seed/lentils/400/300',
    imageHint: 'cooked lentils',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    description: 'A versatile legume, great source of plant-based protein and fiber.',
    nutrients: { fiber: 8, sugar: 0.5, iron: 3.3, calcium: 19, vitaminA: 5, sodium: 2 },
    tags: ['High Protein', 'Vegan', 'High Fiber'],
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/apple/400/300',
    imageHint: 'red apple',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    description: 'A crisp and sweet fruit, rich in fiber and vitamin C.',
    nutrients: { fiber: 2.4, sugar: 10, iron: 0.1, calcium: 6, vitaminA: 3, vitaminC: 4.6, sodium: 1 },
    tags: ['Vegan'],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/banana/400/300',
    imageHint: 'ripe banana',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    description: 'A popular fruit known for its potassium content and natural sweetness.',
    nutrients: { fiber: 2.6, sugar: 12, iron: 0.3, calcium: 5, vitaminA: 4, vitaminC: 8.7, sodium: 1 },
    tags: ['Vegan', 'Energy Boosting'],
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fruit',
    image: 'https://picsum.photos/seed/mango/400/300',
    imageHint: 'sliced mango',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    description: 'A sweet tropical fruit, excellent source of Vitamin A and C.',
    nutrients: { fiber: 1.6, sugar: 14, iron: 0.2, calcium: 11, vitaminA: 54, vitaminC: 36.4, sodium: 1 },
    tags: ['Vegan', 'High Vitamin'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetable',
    image: 'https://picsum.photos/seed/broccoli/400/300',
    imageHint: 'broccoli florets',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    description: 'A green vegetable high in fiber, vitamin C, and vitamin K.',
    nutrients: { fiber: 2.6, sugar: 1.7, iron: 0.7, calcium: 47, vitaminA: 31, vitaminC: 89.2, sodium: 33 },
    tags: ['Vegan', 'Low Carb', 'High Fiber'],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetable',
    image: 'https://picsum.photos/seed/spinach/400/300',
    imageHint: 'fresh spinach',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    description: 'A leafy green vegetable packed with iron, calcium, and vitamins.',
    nutrients: { fiber: 2.2, sugar: 0.4, iron: 2.7, calcium: 99, vitaminA: 469, vitaminC: 28.1, sodium: 79 },
    tags: ['Vegan', 'Low Carb', 'High Iron'],
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice (Cooked)',
    category: 'Grains',
    image: 'https://picsum.photos/seed/rice/400/300',
    imageHint: 'cooked rice',
    calories: 123,
    protein: 2.6,
    carbs: 26,
    fat: 0.9,
    description: 'A whole grain rice with a nutty flavor, high in fiber and minerals.',
    nutrients: { fiber: 1.6, sugar: 0, iron: 0.5, calcium: 10, vitaminA: 0, sodium: 4 },
    tags: ['Vegan'],
  },
  {
    id: 'oats',
    name: 'Oats (Rolled)',
    category: 'Grains',
    image: 'https://picsum.photos/seed/oats/400/300',
    imageHint: 'oats bowl',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    description: 'A versatile whole grain often eaten as oatmeal.',
    nutrients: { fiber: 10.6, sugar: 0, iron: 4.7, calcium: 54, vitaminA: 0, sodium: 2 },
    tags: ['Vegan', 'High Fiber'],
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Beverage',
    image: 'https://picsum.photos/seed/water/400/300',
    imageHint: 'glass water',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    description: 'Essential for hydration.',
    nutrients: { fiber: 0, iron: 0, vitaminA: 0, sodium: 0 },
    tags: ['Vegan', 'Halal'],
  },
  {
    id: 'sobolo',
    name: 'Sobolo (Hibiscus Tea)',
    category: 'Beverage',
    image: 'https://picsum.photos/seed/sobolo/400/300',
    imageHint: 'hibiscus tea',
    calories: 37, // Assuming some sugar is added
    protein: 0.2,
    carbs: 9,
    fat: 0,
    description: 'A refreshing Ghanaian drink made from hibiscus flowers, often flavored with ginger and pineapple.',
    nutrients: { fiber: 0, sugar: 8, iron: 1, vitaminA: 5, vitaminC: 12, sodium: 5 },
    tags: ['Local', 'Vegan'],
  },
];


export const healthQuotes = [
  "The greatest wealth is health.",
  "To keep the body in good health is a duty.",
  "Let food be thy medicine and medicine be thy food.",
  "A healthy outside starts from the inside.",
  "Take care of your body. It's the only place you have to live.",
];

