export const mockUser = {
  name: "Akua",
  email: "akua.g@example.com",
  onboardingCompleted: true,
  profilePictureUrl: "https://picsum.photos/seed/akua/100/100",
};

export const mockFoods = [
  {
    id: "jollof-rice",
    name: "Jollof Rice",
    image: "https://picsum.photos/seed/jollof/400/300",
    imageHint: "jollof rice",
    calories: 350,
    macros: { protein: 8, carbs: 60, fat: 9 },
    description: "A popular West African one-pot rice dish, known for its vibrant red color and deep flavor.",
    nutrients: {
      calories: 350,
      protein: 8,
      carbs: 60,
      fat: 9,
      fiber: 4,
      iron: 2.5,
      vitaminA: 150,
      sodium: 800,
    },
  },
  {
    id: "fufu-and-light-soup",
    name: "Fufu & Light Soup",
    image: "https://picsum.photos/seed/fufu/400/300",
    imageHint: "fufu soup",
    calories: 550,
    macros: { protein: 25, carbs: 80, fat: 15 },
    description: "A staple food made from cassava and plantain, served with a flavorful, spicy tomato-based soup.",
    nutrients: {
      calories: 550,
      protein: 25,
      carbs: 80,
      fat: 15,
      fiber: 8,
      iron: 4,
      vitaminA: 200,
      sodium: 1200,
    },
  },
  {
    id: "grilled-tilapia",
    name: "Grilled Tilapia",
    image: "https://picsum.photos/seed/tilapia/400/300",
    imageHint: "grilled fish",
    calories: 250,
    macros: { protein: 40, carbs: 2, fat: 10 },
    description: "Whole tilapia fish marinated in spices and grilled to perfection, often served with banku or kenkey.",
    nutrients: {
      calories: 250,
      protein: 40,
      carbs: 2,
      fat: 10,
      fiber: 0,
      iron: 1.5,
      vitaminA: 50,
      sodium: 400,
    },
  },
  {
    id: "waakye",
    name: "Waakye",
    image: "https://picsum.photos/seed/waakye/400/300",
    imageHint: "waakye rice",
    calories: 600,
    macros: { protein: 20, carbs: 90, fat: 18 },
    description: "A hearty dish of rice and beans cooked with sorghum leaves, served with various accompaniments.",
    nutrients: {
      calories: 600,
      protein: 20,
      carbs: 90,
      fat: 18,
      fiber: 15,
      iron: 5,
      vitaminA: 10,
      sodium: 1100,
    },
  },
];

export const healthQuotes = [
  "The greatest wealth is health.",
  "To keep the body in good health is a duty.",
  "Let food be thy medicine and medicine be thy food.",
  "A healthy outside starts from the inside.",
  "Take care of your body. It's the only place you have to live.",
];
